---
openapi: 3.0.1
info:
  title: Generated API
  version: "1.0"
paths:
  /app/deploy:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeployInstanceRequest'
      responses:
        200:
          description: OK
  /app/list:
    get:
      responses:
        200:
          description: OK
  /app/stop:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StopInstanceRequest'
      responses:
        200:
          description: OK
  /auto-scale/status:
    get:
      responses:
        200:
          description: OK
  /auto-scale/stop:
    get:
      responses:
        200:
          description: OK
  /auto-scale/update:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MapStringInteger'
      responses:
        200:
          description: OK
  /container-log/logs:
    get:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClientLogRequest'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListLogEntity'
  /container-log/send-log:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClientLogRequest'
      responses:
        201:
          description: Created
  /healthcheck:
    get:
      responses:
        200:
          description: OK
  /logs/{time}:
    get:
      parameters:
      - name: time
        in: path
        required: true
        schema:
          type: string
      responses:
        200:
          description: OK
  /logs/{time}/{filter}:
    get:
      parameters:
      - name: filter
        in: path
        required: true
        schema:
          type: string
      - name: time
        in: path
        required: true
        schema:
          type: string
      responses:
        200:
          description: OK
components:
  schemas:
    DeployInstanceRequest:
      required:
      - app
      type: object
      properties:
        app:
          pattern: \S
          type: string
          nullable: false
    StopInstanceRequest:
      required:
      - id
      type: object
      properties:
        id:
          format: int32
          minimum: 1
          pattern: ^\d{1,2147483647}$
          type: integer
          nullable: false
    MapStringInteger:
      type: object
      additionalProperties:
        format: int32
        type: integer
    ClientLogRequest:
      required:
      - dockerInstance
      - logs
      type: object
      properties:
        dockerInstance:
          pattern: \S
          type: string
          nullable: false
        logs:
          type: array
          items:
            type: object
            properties:
              date:
                type: string
              level:
                type: string
              message:
                type: string
          nullable: false
    ListLogEntity:
      type: array
      items:
        type: object
        properties:
          id:
            format: int64
            type: integer
          appName:
            type: string
          date:
            type: string
          dockerInstance:
            type: string
          level:
            type: string
          message:
            type: string
          squareId:
            format: int32
            type: integer
