image: maven:latest

stages:
  - build
  - test

build_square:
  stage: build
  script:
    - cd square
    - ./mvnw compile

test_square:
  stage: test
  script:
    - cd square
    - ./mvnw test

build_square_client:
  stage: build
  script:
    - cd square-client
    - mvn compile
