default:
  image: maven:latest

stages:
  - build

build_square:
  stage: build
  script:
    - cd square
    - ./mvnw compile

build_square_client:
  stage: build
  script:
    - cd square-client
    - mvn compile
