image: maven:latest

stages:
  - build
  - test

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build_square:
  stage: build
  script:
    - cd square
    - mvn $MAVEN_CLI_OPTS compile

test_square:
  stage: test
  script:
    - cd square
    - mvn $MAVEN_CLI_OPTS test

build_square_client:
  stage: build
  script:
    - cd square-client
    - mvn $MAVEN_CLI_OPTS compile
