image: maven:latest

stages:
  - build
  - test

build_square:
  stage: build
  script:
    - cd square
    - mvn $MAVEN_CLI_OPTS compile

test_square:
  stage: test
  script:
    - cd square
    - mvn $MAVEN_CLI_OPTS test

build_square_client:
  stage: build
  script:
    - cd square-client
    - mvn $MAVEN_CLI_OPTS compile
