FROM node:12.2.0-alpine

WORKDIR /app

COPY todomvc.tar.gz /app/todomvc.tar.gz
CMD tar -xvf todomvc.tar.gz
CMD cd react

RUN npm install --silent
RUN npm install react-scripts@3.0.1 -g --silent

# start app
CMD ["npm", "start"]
