FROM hirokimatsumoto/alpine-openjdk-11
WORKDIR /app
COPY apps/fruitapi.jar /app/app.jar
COPY lib-client/square-client.jar /app/client.jar
ENV SQUARE_HOST=192.168.1.24
ENV SQUARE_PORT=5050
RUN chmod 775 /app
EXPOSE 8080
CMD java -jar app.jar &&
CMD java -jar client.jar

